# Generated by Django 3.2.14 on 2023-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Word')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('language', models.CharField(max_length=5, verbose_name='Language')),
            ],
        ),
    ]
